<?php

namespace App\Livewire;

use App\Models\Visita;
use Cheesegrits\FilamentGoogleMaps\Widgets\MapWidget;
use Illuminate\Support\Carbon;

class MapaDeVisitas extends MapWidget
{
    protected static ?string $heading = null;
    protected static ?string $icon = null;
    protected static ?bool $clustering = true;

    public function getMapConfig(): string
    {
        $config = json_decode(parent::getMapConfig(), true);
        $config['zoom'] = 7;
        $config['center'] = [
            'lat' => -15.793889,
            'lng' => -47.882778,
        ];
        return json_encode($config); // TODO: Change the autogenerated stub
    }

    protected function getData(): array
    {
        $visitas = Visita::query()
            ->with('cliente')
            ->where('status', 'agendada')
            ->where('data', '<=', Carbon::make('today')->add('7 days')->format('Y-m-d'))
            ->get()
            ->toArray();

        $data = [];

        foreach ($visitas as $visita)
        {
            $data[] = [
                'location'  => $visita['cliente']['localizacao'],
                'label' => $visita['cliente']['nome_fantasia'],
                // 'id' => $visita['cliente']['id'],
            ];
        }

        return $data;
    }
}
